version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attornatus
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "oscarfonts/h2:latest"
    container_name: h2-database
    ports:
      - "9092:9092"
    environment:
      - TZ=UTC
      - H2_CONSOLE_ENABLED=true
      - H2_CONSOLE_PORT=9092
      - H2_DATABASE_NAME=attornatus
      - H2_DATABASE_USERNAME=attornatus
      - H2_DATABASE_PASSWORD=password
    volumes:
      - ./data:/data
